version: '3'

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile.django
    volumes:
      -  /static/:/static/
    restart: always
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
    links:
      - web
    volumes:
      - /static/:/static/
    restart: always
    depends_on:
      - web
